// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMedwQl8Q74QRdKsNgoTAlsMa8Rd6_nPs',
    appId: '1:234188519283:web:0eda8c9f727b413b2c3706',
    messagingSenderId: '234188519283',
    projectId: 'lahj-center-d5d0f',
    authDomain: 'lahj-center-d5d0f.firebaseapp.com',
    storageBucket: 'lahj-center-d5d0f.firebasestorage.app',
    measurementId: 'G-5KWHQ054BY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3SNQiL_IbXybWx3efwhUw6VOVdJsQQdA',
    appId: '1:234188519283:android:5ff3a57956e638f02c3706',
    messagingSenderId: '234188519283',
    projectId: 'lahj-center-d5d0f',
    storageBucket: 'lahj-center-d5d0f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjOA_Cf_NTY593Enx25CdBWFxhg3-I9f0',
    appId: '1:234188519283:ios:af6c3e06118573872c3706',
    messagingSenderId: '234188519283',
    projectId: 'lahj-center-d5d0f',
    storageBucket: 'lahj-center-d5d0f.firebasestorage.app',
    iosBundleId: 'com.example.lahijcenter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZzirzReja5xtmPsGTbjc0ryELulYcoIg',
    appId: '1:109978753522:ios:17b2f50814adc80ca2736b',
    messagingSenderId: '109978753522',
    projectId: 'lahj-center',
    storageBucket: 'lahj-center.firebasestorage.app',
    iosBundleId: 'com.example.lahijcenter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAp3IgLZKSzHUmW4z2XIgvI_4-9r0DFwTE',
    appId: '1:109978753522:web:85b81e273eef5315a2736b',
    messagingSenderId: '109978753522',
    projectId: 'lahj-center',
    authDomain: 'lahj-center.firebaseapp.com',
    storageBucket: 'lahj-center.firebasestorage.app',
    measurementId: 'G-ZSQ47YHSHY',
  );
}