// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp3IgLZKSzHUmW4z2XIgvI_4-9r0DFwTE',
    appId: '1:109978753522:web:58117bbec7ef785fa2736b',
    messagingSenderId: '109978753522',
    projectId: 'lahj-center',
    authDomain: 'lahj-center.firebaseapp.com',
    storageBucket: 'lahj-center.firebasestorage.app',
    measurementId: 'G-BJ9HDHV6QG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjQfNGPEkX1-q5RV2rmG93jBsk5eIA0yc',
    appId: '1:109978753522:android:adac76634298d42ca2736b',
    messagingSenderId: '109978753522',
    projectId: 'lahj-center',
    storageBucket: 'lahj-center.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZzirzReja5xtmPsGTbjc0ryELulYcoIg',
    appId: '1:109978753522:ios:17b2f50814adc80ca2736b',
    messagingSenderId: '109978753522',
    projectId: 'lahj-center',
    storageBucket: 'lahj-center.firebasestorage.app',
    iosBundleId: 'com.example.lahijcenter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZzirzReja5xtmPsGTbjc0ryELulYcoIg',
    appId: '1:109978753522:ios:17b2f50814adc80ca2736b',
    messagingSenderId: '109978753522',
    projectId: 'lahj-center',
    storageBucket: 'lahj-center.firebasestorage.app',
    iosBundleId: 'com.example.lahijcenter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAp3IgLZKSzHUmW4z2XIgvI_4-9r0DFwTE',
    appId: '1:109978753522:web:85b81e273eef5315a2736b',
    messagingSenderId: '109978753522',
    projectId: 'lahj-center',
    authDomain: 'lahj-center.firebaseapp.com',
    storageBucket: 'lahj-center.firebasestorage.app',
    measurementId: 'G-ZSQ47YHSHY',
  );
}
